In [30]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from keras.utils import np_utils

# Read dataset to pandas dataframe
dataset = pd.read_csv("data.csv")
dataset.head()

age          workclass   education   education-num       marital-status  \
0   39          State-gov   Bachelors              13        Never-married   
1   50   Self-emp-not-inc   Bachelors              13   Married-civ-spouse   
2   38            Private     HS-grad               9             Divorced   
3   53            Private        11th               7   Married-civ-spouse   
4   28            Private   Bachelors              13   Married-civ-spouse   

           occupation    relationship    race      sex   capital-gain  \
0        Adm-clerical   Not-in-family   White     Male           2174   
1     Exec-managerial         Husband   White     Male              0   
2   Handlers-cleaners   Not-in-family   White     Male              0   
3   Handlers-cleaners         Husband   Black     Male              0   
4      Prof-specialty            Wife   Black   Female              0   

    capital-loss   hours-per-week  native-country  income  
0              0               40   United-States   <=50K  
1              0               13   United-States   <=50K  
2              0               40   United-States   <=50K  
3              0               40   United-States   <=50K  
4              0               40            Cuba   <=50K

In [31]:
#How to pre-process the data?
# fix dataset
# 0,4,9,10,11 is continous so select only descrete columns
cat_columns = []
for i in [1,2,4,5,6,7,8,12,13]:
    cat_columns.append(dataset.columns[i])


In [32]:
# replace empty values
dataset = dataset.replace(" ?", pd.NaT)
dataset.dropna(inplace=True)
#dataset

In [33]:
for i in cat_columns:
    dataset[i] = dataset[i].astype('category')
    
 # represet them using numerical values
for i in cat_columns:
    dataset[i] = pd.Categorical(dataset[i]).codes
    
dataset.dtypes

age                int64
 workclass          int8
 education          int8
 education-num     int64
 marital-status     int8
 occupation         int8
 relationship       int8
 race               int8
 sex                int8
 capital-gain      int64
 capital-loss      int64
 hours-per-week    int64
 native-country     int8
 income             int8
dtype: object

In [34]:
X = np.zeros((13, len(dataset)))
y = np.array(dataset[dataset.columns[13]])


In [35]:
#assign values to the array
for i in range(len(dataset.columns)-1):
    X[i] = np.array(dataset[dataset.columns[i]])
X = X.transpose()

In [36]:
# How to handle the over-fitting problem?
# setting testing and training data limit
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [37]:
y_train

array([0, 0, 0, ..., 0, 0, 1], dtype=int8)

In [38]:
y_test

array([0, 0, 1, ..., 1, 1, 0], dtype=int8)

In [39]:
X_test

array([[29.,  0.,  9., ...,  0., 40., 38.],
       [28.,  2., 11., ...,  0., 40., 38.],
       [36.,  2., 11., ...,  0., 40., 38.],
       ...,
       [36.,  2.,  9., ...,  0., 50., 38.],
       [39.,  2., 11., ...,  0., 40., 38.],
       [23.,  2., 15., ...,  0., 20., 38.]])

In [46]:
# configs
epochs = 50
batch_size = 88
output_classes = 1
layer1 = 13
layer2 = 12
layer3 = 20

# Set up the logistic regression model
model = Sequential()
model.add(Dense(layer2, input_dim=layer1, activation='relu'))
model.add(Dense(layer3, activation='relu'))
model.add(Dense(output_classes, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs)

Epoch 1/50
21113/21113 [==============================] - 1s 33us/step - loss: 4.3236 - acc: 0.5960
Epoch 2/50
21113/21113 [==============================] - 0s 16us/step - loss: 1.2853 - acc: 0.7707
Epoch 3/50
21113/21113 [==============================] - 0s 17us/step - loss: 1.2544 - acc: 0.7744
Epoch 4/50
21113/21113 [==============================] - 0s 16us/step - loss: 1.2337 - acc: 0.7803
Epoch 5/50
21113/21113 [==============================] - 0s 16us/step - loss: 1.3310 - acc: 0.7776
Epoch 6/50
21113/21113 [==============================] - 0s 14us/step - loss: 1.6205 - acc: 0.7625
Epoch 7/50
21113/21113 [==============================] - 0s 14us/step - loss: 1.6186 - acc: 0.7630
Epoch 8/50
21113/21113 [==============================] - 0s 13us/step - loss: 1.6163 - acc: 0.7635
Epoch 9/50
21113/21113 [==============================] - 0s 12us/step - loss: 1.6120 - acc: 0.7647
Epoch 10/50
21113/21113 [==============================] - 0s 12us/step - loss: 1.6127 - acc: 0.7658

In [47]:
evaluation = model.evaluate(X_test, y_test, verbose=1)

9049/9049 [==============================] - 0s 26us/step


In [48]:
evaluation[1]

0.7871588020644039